service: memstress-${opt:suffix}

provider:
  name: aws
  stackName: memstress-${opt:suffix}
  project: faastest
  stage: dev
  versionFunctions: false
  timeout: 20

functions:
  node12-memorystress-128:
    name: memstress-node12-128mb-${opt:suffix}
    description: memory intensive function 128mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 128

  node12-memorystress-256:
    name: memstress-node12-256mb-${opt:suffix}
    description: memory intensive function 256mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 256

  node12-memorystress-512:
    name: memstress-node12-512mb-${opt:suffix}
    description: memory intensive function 512mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 512

  node12-memorystress-1024:
    name: memstress-node12-1024mb-${opt:suffix}
    description: memory intensive function 1024mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 1024

  node12-memorystress-1536:
    name: memstress-node12-1536mb-${opt:suffix}
    description: memory intensive function 1536mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 1536
