apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sleep-node13
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/nropatas/faastest-sleep-node13
