# Welcome to Serverless!
#
# For full config options, check the kubeless plugin docs:
#    https://github.com/serverless/serverless-kubeless
#
# For documentation on kubeless itself:
#    http://kubeless.io

# Update the service name below with your own service name
service: kubeless

# Please ensure the serverless-kubeless provider plugin is installed globally.
# $ npm install -g serverless-kubeless
#
# ...before installing project dependencies to register this provider.
# $ npm install

provider:
  name: kubeless
  runtime: nodejs12
  hostname: example.com

plugins:
  - serverless-kubeless

functions:
  kubeless-simple:
    handler: handler.simple
    # memorySize: 256M # Maximum memory
    events:
      - http:
          path: /kubeless-simple
