service: faas

provider:
  name: aws
  timeout: 300
  region: eu-central-1
  stage: mark
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "cloudformation:DescribeStacks"
        - "lambda:InvokeFunction"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

functions:

  empty:
    runtime: nodejs12.x
    memorySize: 1024
    handler: src/handlers/empty.empty

  simpleInitiator:
    runtime: nodejs12.x
    memorySize: 1024
    handler: src/handlers/simpleInitiator.simpleInitiator
    events:
      - http:
          path: simpleInitiator
          method: get



  empty-js-128:
    runtime: nodejs12.x
    memorySize: 128
    handler: src/handlers/empty.empty

  empty-js-256:
    runtime: nodejs12.x
    memorySize: 256
    handler: src/handlers/empty.empty

  empty-js-512:
    runtime: nodejs12.x
    memorySize: 512
    handler: src/handlers/empty.empty

  empty-js-1024:
    runtime: nodejs12.x
    memorySize: 1024
    handler: src/handlers/empty.empty
    events:
      - http:
          path: empty-js-1024
          method: get

  empty-py-1024:
    runtime: python2.7
    memorySize: 1024
    handler: src/handlers/empty.empty

  empty-java-1024:
    runtime: java11
    memorySize: 1024
    package:
      artifact: build/distributions/faasmark.zip
    handler: com.serverless.Empty::handleRequest

  aspectInitiator:
    runtime: nodejs12.x
    memorySize: 1024
    handler: src/handlers/aspectInitiator.aspectInitiator



  sleeper:
    runtime: nodejs12.x
    memorySize: 1024
    handler: src/handlers/sleeper.sleeper

  concurrencyInitiator:
    runtime: nodejs12.x
    memorySize: 1024
    handler: src/handlers/concurrencyInitiator.concurrencyInitiator
