service: iostress
provider:
  name: openwhisk
  project: faastest
  stage: dev
  ignore_certs: true

functions:
  iostress-node12-128mb:
    name: iostress-node12-128mb
    description: iostress function 128mb
    runtime: nodejs:12
    handler: handler.iostress
    memory: 128
    annotations:
      web-export: true

  iostress-node12-256mb:
    name: iostress-node12-256mb
    description: iostress function 256mb
    runtime: nodejs:12
    handler: handler.iostress
    memory: 256
    annotations:
      web-export: true

  iostress-node12-512mb:
    name: iostress-node12-512mb
    description: iostress function 512mb
    runtime: nodejs:12
    handler: handler.iostress
    memory: 512
    annotations:
      web-export: true

plugins:
  - serverless-openwhisk
