service: netstress
provider:
  name: openwhisk
  project: faastest
  stage: dev
  ignore_certs: true

functions:
  netstress-node12-128mb:
    name: netstress-node12-128mb
    description: netstress function 128mb
    runtime: nodejs:12
    handler: handler.netstress
    memory: 128
    annotations:
      web-export: true

  netstress-node12-256mb:
    name: netstress-node12-256mb
    description: netstress function 256mb
    runtime: nodejs:12
    handler: handler.netstress
    memory: 256
    annotations:
      web-export: true

  netstress-node12-512mb:
    name: netstress-node12-512mb
    description: netstress function 512mb
    runtime: nodejs:12
    handler: handler.netstress
    memory: 512
    annotations:
      web-export: true

plugins:
  - serverless-openwhisk
