service: logging-${opt:suffix}

provider:
  name: aws
  stackName: logging-${opt:suffix}
  project: faastest
  stage: dev
  versionFunctions: false
  timeout: 20

functions:
  node12-memory-128:
    name: logging-node12-128mb-${opt:suffix}
    description: io intensive function 128mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 128

  node12-memory-256:
    name: logging-node12-256mb-${opt:suffix}
    description: io intensive function 256mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 256

  node12-memory-512:
    name: logging-node12-512mb-${opt:suffix}
    description: io intensive function 512mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 512

  node12-memory-1024:
    name: logging-node12-1024mb-${opt:suffix}
    description: io intensive function 1024mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 1024

  node12-memory-1536:
    name: logging-node12-1536mb-${opt:suffix}
    description: io intensive function 1536mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 1536
