apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-simple
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        # autoscaling.knative.dev/maxScale: "10"
        # autoscaling.knative.dev/metric: cpu
        # autoscaling.knative.dev/target: "80"
        # autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
    spec:
      # containerConcurrency: 10
      containers:
        - image: docker.io/nropatas/knative-simple
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
