apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-simple
  namespace: default
spec:
  template:
    # metadata:
    #   annotations:
    #     autoscaling.knative.dev/metric: cpu
    #     autoscaling.knative.dev/target: "50"
    #     autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
    spec:
      containers:
        - image: docker.io/nropatas/knative-simple
