apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-simple
  namespace: default
spec:
  template:
    # metadata:
    #   annotations:
    #     autoscaling.knative.dev/metric: cpu
    #     autoscaling.knative.dev/target: "50"
    #     autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
        # autoscaling.knative.dev/minScale: "2"
        # autoscaling.knative.dev/maxScale: "10"
    spec:
      # containerConcurrency: 10
      containers:
        - image: docker.io/nropatas/knative-simple
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "100m"
