service: singlefunction-${opt:suffix}

provider:
  name: aws
  region: eu-central-1
  stackName: singlefunction-${opt:suffix}
  project: faastest
  stage: dev
  versionFunctions: false
  timeout: 20

functions:
  node12-memory-128:
    name: sleep-node12-128mb-${opt:suffix}
    description: sleep function 128mb
    runtime: nodejs12.x
    handler: nodejs/handler.hello
    memorySize: 128

