service: largeresponse-${opt:suffix}

provider:
  name: aws
  project: faastest
  stackName: largeresponse-${opt:suffix}
  stage: dev
  versionFunctions: false
  timeout: 20

functions:
  node12-memory-128:
    name: largeresponse-node12-128mb-${opt:suffix}
    description: function returning a large response 128mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 128

  node12-memory-256:
    name: largeresponse-node12-256mb-${opt:suffix}
    description: function returning a large response 256mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 256

  node12-memory-512:
    name: largeresponse-node12-512mb-${opt:suffix}
    description: function returning a large response 512mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 512

  node12-memory-1024:
    name: largeresponse-node12-1024mb-${opt:suffix}
    description: function returning a large response 1024mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 1024

  node12-memory-1536:
    name: largeresponse-node12-1536mb-${opt:suffix}
    description: function returning a large response 1536mb
    runtime: nodejs12.x
    handler: nodejs/handler.handler
    memorySize: 1536
