apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memstress-node13-128mb
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/nropatas/faastest-memstress-node13
          env:
            - name: FUNCTION_MEMORY_SIZE
              value: "128"
          resources:
            limits:
              memory: "128Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memstress-node13-256mb
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/nropatas/faastest-memstress-node13
          env:
            - name: FUNCTION_MEMORY_SIZE
              value: "256"
          resources:
            limits:
              memory: "256Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memstress-node13-512mb
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/nropatas/faastest-memstress-node13
          env:
            - name: FUNCTION_MEMORY_SIZE
              value: "512"
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memstress-node13-1024mb
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/nropatas/faastest-memstress-node13
          env:
            - name: FUNCTION_MEMORY_SIZE
              value: "1024"
          resources:
            limits:
              memory: "1024Mi"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memstress-node13-2048mb
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/nropatas/faastest-memstress-node13
          env:
            - name: FUNCTION_MEMORY_SIZE
              value: "2048"
          resources:
            limits:
              memory: "2048Mi"
