service: openwhisk
provider:
  name: openwhisk
  ignore_certs: true

functions:
  openwhisk-simple:
    name: openwhisk-simple
    handler: handler.simple
    annotations:
      web-export: true

plugins:
  - serverless-openwhisk
