apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sleep-node13-128mb
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/nropatas/faastest-sleep-node13
          resources:
            limits:
              memory: "128Mi"
